from PyQt5 import QtCore, QtGui, QtWidgets


class Ui(object):
    def setupUi(self, ConfigureWindow):
        ConfigureWindow.setObjectName("ConfigureWindow")
        ConfigureWindow.resize(640, 380)
        ConfigureWindow.setMinimumSize(QtCore.QSize(640, 380))
        ConfigureWindow.setMaximumSize(QtCore.QSize(640, 380))
        self.centralwidget = QtWidgets.QWidget(ConfigureWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 640, 380))
        self.frame.setMinimumSize(QtCore.QSize(640, 380))
        self.frame.setMaximumSize(QtCore.QSize(640, 380))
        self.frame.setStyleSheet("background: darkblue")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.ScoreBtn = QtWidgets.QPushButton(self.frame)
        self.ScoreBtn.setGeometry(QtCore.QRect(1, 140, 641, 33))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ScoreBtn.setFont(font)
        self.ScoreBtn.setStyleSheet("border: none;\n"
"color: green;\n"
"QPushButton\n"
"{\n"
"    color: white;\n"
"}")
        self.ScoreBtn.setObjectName("ScoreBtn")
        self.ConfigBtn = QtWidgets.QPushButton(self.frame)
        self.ConfigBtn.setGeometry(QtCore.QRect(0, 180, 641, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ConfigBtn.setFont(font)
        self.ConfigBtn.setStyleSheet("border: none;\n"
"color: green;\n"
"QPushButton\n"
"{\n"
"    color: white;\n"
"}")
        self.ConfigBtn.setObjectName("ConfigBtn")
        self.ReturnBtn = QtWidgets.QPushButton(self.frame)
        self.ReturnBtn.setGeometry(QtCore.QRect(-110, 320, 641, 33))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ReturnBtn.setFont(font)
        self.ReturnBtn.setStyleSheet("border: none;\n"
"color: green;\n"
"QPushButton\n"
"{\n"
"    color: white;\n"
"}")
        self.ReturnBtn.setAutoDefault(False)
        self.ReturnBtn.setObjectName("ReturnBtn")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(10, 30, 621, 101))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(26)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: green;\n"
"")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.ConfigBtn_2 = QtWidgets.QPushButton(self.frame)
        self.ConfigBtn_2.setGeometry(QtCore.QRect(0, 230, 641, 33))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ConfigBtn_2.setFont(font)
        self.ConfigBtn_2.setStyleSheet("border: none;\n"
"color: green;\n"
"QPushButton\n"
"{\n"
"    color: white;\n"
"}")
        self.ConfigBtn_2.setObjectName("ConfigBtn_2")
        self.ConfigBtn_3 = QtWidgets.QPushButton(self.frame)
        self.ConfigBtn_3.setGeometry(QtCore.QRect(0, 280, 641, 33))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ConfigBtn_3.setFont(font)
        self.ConfigBtn_3.setStyleSheet("border: none;\n"
"color: green;\n"
"QPushButton\n"
"{\n"
"    color: white;\n"
"}")
        self.ConfigBtn_3.setObjectName("ConfigBtn_3")
        self.checkBox = QtWidgets.QCheckBox(self.frame)
        self.checkBox.setGeometry(QtCore.QRect(450, 150, 70, 17))
        self.checkBox.setText("")
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_2.setGeometry(QtCore.QRect(450, 190, 70, 17))
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_3.setGeometry(QtCore.QRect(450, 240, 70, 17))
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame)
        self.checkBox_4.setGeometry(QtCore.QRect(450, 290, 70, 17))
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(30, 10, 12, 22))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: orange;\n"
"")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 14, 22))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: red;\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(40, 10, 13, 22))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: Yellow;\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(60, 10, 9, 22))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: blue;\n"
"")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(50, 10, 12, 22))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: green;\n"
"")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(70, 10, 12, 22))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: purple;\n"
"")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.ConfigBtn_2.raise_()
        self.ScoreBtn.raise_()
        self.ConfigBtn.raise_()
        self.ReturnBtn.raise_()
        self.label_8.raise_()
        self.ConfigBtn_3.raise_()
        self.checkBox_2.raise_()
        self.checkBox_3.raise_()
        self.checkBox_4.raise_()
        self.checkBox.raise_()
        self.label_9.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_7.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        ConfigureWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ConfigureWindow)
        QtCore.QMetaObject.connectSlotsByName(ConfigureWindow)

    def retranslateUi(self, ConfigureWindow):
        _translate = QtCore.QCoreApplication.translate
        ConfigureWindow.setWindowTitle(_translate("ConfigureWindow", "MainWindow"))
        self.ScoreBtn.setText(_translate("ConfigureWindow", "Field Size"))
        self.ConfigBtn.setText(_translate("ConfigureWindow", "Game Level"))
        self.ReturnBtn.setText(_translate("ConfigureWindow", "Return"))
        self.label_8.setText(_translate("ConfigureWindow", "Configuration"))
        self.ConfigBtn_2.setText(_translate("ConfigureWindow", "Extended Game"))
        self.ConfigBtn_3.setText(_translate("ConfigureWindow", "Player"))
        self.label_9.setText(_translate("ConfigureWindow", "e"))
        self.label_3.setText(_translate("ConfigureWindow", "T"))
        self.label_4.setText(_translate("ConfigureWindow", "t"))
        self.label_7.setText(_translate("ConfigureWindow", "i"))
        self.label_5.setText(_translate("ConfigureWindow", "r"))
        self.label_6.setText(_translate("ConfigureWindow", "s"))