# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Game.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 380)
        MainWindow.setMinimumSize(QtCore.QSize(640, 380))
        MainWindow.setMaximumSize(QtCore.QSize(640, 380))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(640, 380))
        self.centralwidget.setMaximumSize(QtCore.QSize(640, 380))
        self.centralwidget.setObjectName("centralwidget")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 640, 380))
        self.frame_3.setMinimumSize(QtCore.QSize(640, 380))
        self.frame_3.setMaximumSize(QtCore.QSize(640, 380))
        self.frame_3.setStyleSheet("background: darkblue")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.ExitBtn_5 = QtWidgets.QPushButton(self.frame_3)
        self.ExitBtn_5.setGeometry(QtCore.QRect(510, 320, 71, 33))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ExitBtn_5.setFont(font)
        self.ExitBtn_5.setStyleSheet("border: none;\n"
"color: green;\n"
"QPushButton\n"
"{\n"
"    color: white;\n"
"}")
        self.ExitBtn_5.setAutoDefault(False)
        self.ExitBtn_5.setObjectName("ExitBtn_5")
        self.graphicsView = QtWidgets.QGraphicsView(self.frame_3)
        self.graphicsView.setGeometry(QtCore.QRect(10, 40, 621, 321))
        self.graphicsView.setObjectName("graphicsView")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 14, 22))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: red;\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(50, 10, 12, 22))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: green;\n"
"")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(60, 10, 9, 22))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: blue;\n"
"")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(70, 10, 12, 22))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: purple;\n"
"")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(40, 10, 13, 22))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: Yellow;\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(30, 10, 12, 22))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: orange;\n"
"")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.ExitBtn_6 = QtWidgets.QPushButton(self.frame_3)
        self.ExitBtn_6.setGeometry(QtCore.QRect(510, 290, 71, 33))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ExitBtn_6.setFont(font)
        self.ExitBtn_6.setStyleSheet("border: none;\n"
"color: green;\n"
"QPushButton\n"
"{\n"
"    color: white;\n"
"}")
        self.ExitBtn_6.setAutoDefault(False)
        self.ExitBtn_6.setObjectName("ExitBtn_6")
        self.ExitBtn_7 = QtWidgets.QPushButton(self.frame_3)
        self.ExitBtn_7.setGeometry(QtCore.QRect(20, 50, 114, 33))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ExitBtn_7.setFont(font)
        self.ExitBtn_7.setStyleSheet("border: none;\n"
"color: green;\n"
"QPushButton\n"
"{\n"
"    color: white;\n"
"}")
        self.ExitBtn_7.setAutoDefault(False)
        self.ExitBtn_7.setObjectName("ExitBtn_7")
        self.ExitBtn_8 = QtWidgets.QPushButton(self.frame_3)
        self.ExitBtn_8.setGeometry(QtCore.QRect(540, 50, 77, 33))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ExitBtn_8.setFont(font)
        self.ExitBtn_8.setStyleSheet("border: none;\n"
"color: green;\n"
"QPushButton\n"
"{\n"
"    color: white;\n"
"}")
        self.ExitBtn_8.setAutoDefault(False)
        self.ExitBtn_8.setObjectName("ExitBtn_8")
        self.graphicsView.raise_()
        self.ExitBtn_5.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        self.label_7.raise_()
        self.label_6.raise_()
        self.label_4.raise_()
        self.label_8.raise_()
        self.ExitBtn_6.raise_()
        self.ExitBtn_7.raise_()
        self.ExitBtn_8.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ExitBtn_5.setText(_translate("MainWindow", "Score:"))
        self.label_3.setText(_translate("MainWindow", "T"))
        self.label_5.setText(_translate("MainWindow", "r"))
        self.label_7.setText(_translate("MainWindow", "i"))
        self.label_6.setText(_translate("MainWindow", "s"))
        self.label_4.setText(_translate("MainWindow", "t"))
        self.label_8.setText(_translate("MainWindow", "e"))
        self.ExitBtn_6.setText(_translate("MainWindow", "Lines:"))
        self.ExitBtn_7.setText(_translate("MainWindow", "Gamemode:"))
        self.ExitBtn_8.setText(_translate("MainWindow", "Normal:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
