# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Score.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 380)
        MainWindow.setMinimumSize(QtCore.QSize(640, 380))
        MainWindow.setMaximumSize(QtCore.QSize(640, 380))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 640, 380))
        self.frame_2.setMinimumSize(QtCore.QSize(640, 380))
        self.frame_2.setMaximumSize(QtCore.QSize(640, 380))
        self.frame_2.setStyleSheet("background: darkblue")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.ExitBtn_3 = QtWidgets.QPushButton(self.frame_2)
        self.ExitBtn_3.setGeometry(QtCore.QRect(-110, 320, 641, 33))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ExitBtn_3.setFont(font)
        self.ExitBtn_3.setStyleSheet("border: none;\n"
"color: green;\n"
"QPushButton\n"
"{\n"
"    color: white;\n"
"}")
        self.ExitBtn_3.setAutoDefault(False)
        self.ExitBtn_3.setObjectName("ExitBtn_3")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(10, 20, 621, 101))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(26)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: green;\n"
"")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.tableView = QtWidgets.QTableView(self.frame_2)
        self.tableView.setGeometry(QtCore.QRect(90, 110, 441, 211))
        self.tableView.setObjectName("tableView")
        self.StartBtn = QtWidgets.QPushButton(self.frame_2)
        self.StartBtn.setGeometry(QtCore.QRect(100, 120, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StartBtn.setFont(font)
        self.StartBtn.setMouseTracking(False)
        self.StartBtn.setStyleSheet("border: none;\n"
"color: green;\n"
"\n"
"QPushButton::pressed \n"
"{ \n"
"    color: white;\n"
" }\n"
"\n"
"QPushButton::hover\n"
"{\n"
"     text-decoration: underline; \n"
"    text-decoration-color: green;    \n"
"}")
        self.StartBtn.setCheckable(False)
        self.StartBtn.setObjectName("StartBtn")
        self.StartBtn_2 = QtWidgets.QPushButton(self.frame_2)
        self.StartBtn_2.setGeometry(QtCore.QRect(100, 160, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StartBtn_2.setFont(font)
        self.StartBtn_2.setMouseTracking(False)
        self.StartBtn_2.setStyleSheet("border: none;\n"
"color: green;\n"
"\n"
"QPushButton::pressed \n"
"{ \n"
"    color: white;\n"
" }\n"
"\n"
"QPushButton::hover\n"
"{\n"
"     text-decoration: underline; \n"
"    text-decoration-color: green;    \n"
"}")
        self.StartBtn_2.setCheckable(False)
        self.StartBtn_2.setObjectName("StartBtn_2")
        self.StartBtn_3 = QtWidgets.QPushButton(self.frame_2)
        self.StartBtn_3.setGeometry(QtCore.QRect(100, 200, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StartBtn_3.setFont(font)
        self.StartBtn_3.setMouseTracking(False)
        self.StartBtn_3.setStyleSheet("border: none;\n"
"color: green;\n"
"\n"
"QPushButton::pressed \n"
"{ \n"
"    color: white;\n"
" }\n"
"\n"
"QPushButton::hover\n"
"{\n"
"     text-decoration: underline; \n"
"    text-decoration-color: green;    \n"
"}")
        self.StartBtn_3.setCheckable(False)
        self.StartBtn_3.setObjectName("StartBtn_3")
        self.StartBtn_4 = QtWidgets.QPushButton(self.frame_2)
        self.StartBtn_4.setGeometry(QtCore.QRect(330, 120, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StartBtn_4.setFont(font)
        self.StartBtn_4.setMouseTracking(False)
        self.StartBtn_4.setStyleSheet("border: none;\n"
"color: green;\n"
"\n"
"QPushButton::pressed \n"
"{ \n"
"    color: white;\n"
" }\n"
"\n"
"QPushButton::hover\n"
"{\n"
"     text-decoration: underline; \n"
"    text-decoration-color: green;    \n"
"}")
        self.StartBtn_4.setCheckable(False)
        self.StartBtn_4.setObjectName("StartBtn_4")
        self.StartBtn_5 = QtWidgets.QPushButton(self.frame_2)
        self.StartBtn_5.setGeometry(QtCore.QRect(330, 160, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StartBtn_5.setFont(font)
        self.StartBtn_5.setMouseTracking(False)
        self.StartBtn_5.setStyleSheet("border: none;\n"
"color: green;\n"
"\n"
"QPushButton::pressed \n"
"{ \n"
"    color: white;\n"
" }\n"
"\n"
"QPushButton::hover\n"
"{\n"
"     text-decoration: underline; \n"
"    text-decoration-color: green;    \n"
"}")
        self.StartBtn_5.setCheckable(False)
        self.StartBtn_5.setObjectName("StartBtn_5")
        self.StartBtn_6 = QtWidgets.QPushButton(self.frame_2)
        self.StartBtn_6.setGeometry(QtCore.QRect(330, 240, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StartBtn_6.setFont(font)
        self.StartBtn_6.setMouseTracking(False)
        self.StartBtn_6.setStyleSheet("border: none;\n"
"color: green;\n"
"\n"
"QPushButton::pressed \n"
"{ \n"
"    color: white;\n"
" }\n"
"\n"
"QPushButton::hover\n"
"{\n"
"     text-decoration: underline; \n"
"    text-decoration-color: green;    \n"
"}")
        self.StartBtn_6.setCheckable(False)
        self.StartBtn_6.setObjectName("StartBtn_6")
        self.StartBtn_7 = QtWidgets.QPushButton(self.frame_2)
        self.StartBtn_7.setGeometry(QtCore.QRect(330, 200, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StartBtn_7.setFont(font)
        self.StartBtn_7.setMouseTracking(False)
        self.StartBtn_7.setStyleSheet("border: none;\n"
"color: green;\n"
"\n"
"QPushButton::pressed \n"
"{ \n"
"    color: white;\n"
" }\n"
"\n"
"QPushButton::hover\n"
"{\n"
"     text-decoration: underline; \n"
"    text-decoration-color: green;    \n"
"}")
        self.StartBtn_7.setCheckable(False)
        self.StartBtn_7.setObjectName("StartBtn_7")
        self.StartBtn_8 = QtWidgets.QPushButton(self.frame_2)
        self.StartBtn_8.setGeometry(QtCore.QRect(100, 240, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StartBtn_8.setFont(font)
        self.StartBtn_8.setMouseTracking(False)
        self.StartBtn_8.setStyleSheet("border: none;\n"
"color: green;\n"
"\n"
"QPushButton::pressed \n"
"{ \n"
"    color: white;\n"
" }\n"
"\n"
"QPushButton::hover\n"
"{\n"
"     text-decoration: underline; \n"
"    text-decoration-color: green;    \n"
"}")
        self.StartBtn_8.setCheckable(False)
        self.StartBtn_8.setObjectName("StartBtn_8")
        self.StartBtn_9 = QtWidgets.QPushButton(self.frame_2)
        self.StartBtn_9.setGeometry(QtCore.QRect(100, 280, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StartBtn_9.setFont(font)
        self.StartBtn_9.setMouseTracking(False)
        self.StartBtn_9.setStyleSheet("border: none;\n"
"color: green;\n"
"\n"
"QPushButton::pressed \n"
"{ \n"
"    color: white;\n"
" }\n"
"\n"
"QPushButton::hover\n"
"{\n"
"     text-decoration: underline; \n"
"    text-decoration-color: green;    \n"
"}")
        self.StartBtn_9.setCheckable(False)
        self.StartBtn_9.setObjectName("StartBtn_9")
        self.StartBtn_10 = QtWidgets.QPushButton(self.frame_2)
        self.StartBtn_10.setGeometry(QtCore.QRect(330, 280, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StartBtn_10.setFont(font)
        self.StartBtn_10.setMouseTracking(False)
        self.StartBtn_10.setStyleSheet("border: none;\n"
"color: green;\n"
"\n"
"QPushButton::pressed \n"
"{ \n"
"    color: white;\n"
" }\n"
"\n"
"QPushButton::hover\n"
"{\n"
"     text-decoration: underline; \n"
"    text-decoration-color: green;    \n"
"}")
        self.StartBtn_10.setCheckable(False)
        self.StartBtn_10.setObjectName("StartBtn_10")
        self.StartBtn_11 = QtWidgets.QPushButton(self.frame_2)
        self.StartBtn_11.setGeometry(QtCore.QRect(160, 120, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StartBtn_11.setFont(font)
        self.StartBtn_11.setMouseTracking(False)
        self.StartBtn_11.setStyleSheet("border: none;\n"
"color: green;\n"
"\n"
"QPushButton::pressed \n"
"{ \n"
"    color: white;\n"
" }\n"
"\n"
"QPushButton::hover\n"
"{\n"
"     text-decoration: underline; \n"
"    text-decoration-color: green;    \n"
"}")
        self.StartBtn_11.setCheckable(False)
        self.StartBtn_11.setObjectName("StartBtn_11")
        self.StartBtn_12 = QtWidgets.QPushButton(self.frame_2)
        self.StartBtn_12.setGeometry(QtCore.QRect(220, 120, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StartBtn_12.setFont(font)
        self.StartBtn_12.setMouseTracking(False)
        self.StartBtn_12.setStyleSheet("border: none;\n"
"color: green;\n"
"\n"
"QPushButton::pressed \n"
"{ \n"
"    color: white;\n"
" }\n"
"\n"
"QPushButton::hover\n"
"{\n"
"     text-decoration: underline; \n"
"    text-decoration-color: green;    \n"
"}")
        self.StartBtn_12.setCheckable(False)
        self.StartBtn_12.setObjectName("StartBtn_12")
        self.StartBtn_13 = QtWidgets.QPushButton(self.frame_2)
        self.StartBtn_13.setGeometry(QtCore.QRect(220, 160, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StartBtn_13.setFont(font)
        self.StartBtn_13.setMouseTracking(False)
        self.StartBtn_13.setStyleSheet("border: none;\n"
"color: green;\n"
"\n"
"QPushButton::pressed \n"
"{ \n"
"    color: white;\n"
" }\n"
"\n"
"QPushButton::hover\n"
"{\n"
"     text-decoration: underline; \n"
"    text-decoration-color: green;    \n"
"}")
        self.StartBtn_13.setCheckable(False)
        self.StartBtn_13.setObjectName("StartBtn_13")
        self.StartBtn_14 = QtWidgets.QPushButton(self.frame_2)
        self.StartBtn_14.setGeometry(QtCore.QRect(160, 160, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StartBtn_14.setFont(font)
        self.StartBtn_14.setMouseTracking(False)
        self.StartBtn_14.setStyleSheet("border: none;\n"
"color: green;\n"
"\n"
"QPushButton::pressed \n"
"{ \n"
"    color: white;\n"
" }\n"
"\n"
"QPushButton::hover\n"
"{\n"
"     text-decoration: underline; \n"
"    text-decoration-color: green;    \n"
"}")
        self.StartBtn_14.setCheckable(False)
        self.StartBtn_14.setObjectName("StartBtn_14")
        self.StartBtn_15 = QtWidgets.QPushButton(self.frame_2)
        self.StartBtn_15.setGeometry(QtCore.QRect(220, 200, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StartBtn_15.setFont(font)
        self.StartBtn_15.setMouseTracking(False)
        self.StartBtn_15.setStyleSheet("border: none;\n"
"color: green;\n"
"\n"
"QPushButton::pressed \n"
"{ \n"
"    color: white;\n"
" }\n"
"\n"
"QPushButton::hover\n"
"{\n"
"     text-decoration: underline; \n"
"    text-decoration-color: green;    \n"
"}")
        self.StartBtn_15.setCheckable(False)
        self.StartBtn_15.setObjectName("StartBtn_15")
        self.StartBtn_16 = QtWidgets.QPushButton(self.frame_2)
        self.StartBtn_16.setGeometry(QtCore.QRect(160, 200, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StartBtn_16.setFont(font)
        self.StartBtn_16.setMouseTracking(False)
        self.StartBtn_16.setStyleSheet("border: none;\n"
"color: green;\n"
"\n"
"QPushButton::pressed \n"
"{ \n"
"    color: white;\n"
" }\n"
"\n"
"QPushButton::hover\n"
"{\n"
"     text-decoration: underline; \n"
"    text-decoration-color: green;    \n"
"}")
        self.StartBtn_16.setCheckable(False)
        self.StartBtn_16.setObjectName("StartBtn_16")
        self.StartBtn_17 = QtWidgets.QPushButton(self.frame_2)
        self.StartBtn_17.setGeometry(QtCore.QRect(220, 240, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StartBtn_17.setFont(font)
        self.StartBtn_17.setMouseTracking(False)
        self.StartBtn_17.setStyleSheet("border: none;\n"
"color: green;\n"
"\n"
"QPushButton::pressed \n"
"{ \n"
"    color: white;\n"
" }\n"
"\n"
"QPushButton::hover\n"
"{\n"
"     text-decoration: underline; \n"
"    text-decoration-color: green;    \n"
"}")
        self.StartBtn_17.setCheckable(False)
        self.StartBtn_17.setObjectName("StartBtn_17")
        self.StartBtn_18 = QtWidgets.QPushButton(self.frame_2)
        self.StartBtn_18.setGeometry(QtCore.QRect(160, 240, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StartBtn_18.setFont(font)
        self.StartBtn_18.setMouseTracking(False)
        self.StartBtn_18.setStyleSheet("border: none;\n"
"color: green;\n"
"\n"
"QPushButton::pressed \n"
"{ \n"
"    color: white;\n"
" }\n"
"\n"
"QPushButton::hover\n"
"{\n"
"     text-decoration: underline; \n"
"    text-decoration-color: green;    \n"
"}")
        self.StartBtn_18.setCheckable(False)
        self.StartBtn_18.setObjectName("StartBtn_18")
        self.StartBtn_19 = QtWidgets.QPushButton(self.frame_2)
        self.StartBtn_19.setGeometry(QtCore.QRect(160, 280, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StartBtn_19.setFont(font)
        self.StartBtn_19.setMouseTracking(False)
        self.StartBtn_19.setStyleSheet("border: none;\n"
"color: green;\n"
"\n"
"QPushButton::pressed \n"
"{ \n"
"    color: white;\n"
" }\n"
"\n"
"QPushButton::hover\n"
"{\n"
"     text-decoration: underline; \n"
"    text-decoration-color: green;    \n"
"}")
        self.StartBtn_19.setCheckable(False)
        self.StartBtn_19.setObjectName("StartBtn_19")
        self.StartBtn_20 = QtWidgets.QPushButton(self.frame_2)
        self.StartBtn_20.setGeometry(QtCore.QRect(220, 280, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StartBtn_20.setFont(font)
        self.StartBtn_20.setMouseTracking(False)
        self.StartBtn_20.setStyleSheet("border: none;\n"
"color: green;\n"
"\n"
"QPushButton::pressed \n"
"{ \n"
"    color: white;\n"
" }\n"
"\n"
"QPushButton::hover\n"
"{\n"
"     text-decoration: underline; \n"
"    text-decoration-color: green;    \n"
"}")
        self.StartBtn_20.setCheckable(False)
        self.StartBtn_20.setObjectName("StartBtn_20")
        self.StartBtn_21 = QtWidgets.QPushButton(self.frame_2)
        self.StartBtn_21.setGeometry(QtCore.QRect(380, 120, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StartBtn_21.setFont(font)
        self.StartBtn_21.setMouseTracking(False)
        self.StartBtn_21.setStyleSheet("border: none;\n"
"color: green;\n"
"\n"
"QPushButton::pressed \n"
"{ \n"
"    color: white;\n"
" }\n"
"\n"
"QPushButton::hover\n"
"{\n"
"     text-decoration: underline; \n"
"    text-decoration-color: green;    \n"
"}")
        self.StartBtn_21.setCheckable(False)
        self.StartBtn_21.setObjectName("StartBtn_21")
        self.StartBtn_22 = QtWidgets.QPushButton(self.frame_2)
        self.StartBtn_22.setGeometry(QtCore.QRect(440, 120, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StartBtn_22.setFont(font)
        self.StartBtn_22.setMouseTracking(False)
        self.StartBtn_22.setStyleSheet("border: none;\n"
"color: green;\n"
"\n"
"QPushButton::pressed \n"
"{ \n"
"    color: white;\n"
" }\n"
"\n"
"QPushButton::hover\n"
"{\n"
"     text-decoration: underline; \n"
"    text-decoration-color: green;    \n"
"}")
        self.StartBtn_22.setCheckable(False)
        self.StartBtn_22.setObjectName("StartBtn_22")
        self.StartBtn_23 = QtWidgets.QPushButton(self.frame_2)
        self.StartBtn_23.setGeometry(QtCore.QRect(380, 160, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StartBtn_23.setFont(font)
        self.StartBtn_23.setMouseTracking(False)
        self.StartBtn_23.setStyleSheet("border: none;\n"
"color: green;\n"
"\n"
"QPushButton::pressed \n"
"{ \n"
"    color: white;\n"
" }\n"
"\n"
"QPushButton::hover\n"
"{\n"
"     text-decoration: underline; \n"
"    text-decoration-color: green;    \n"
"}")
        self.StartBtn_23.setCheckable(False)
        self.StartBtn_23.setObjectName("StartBtn_23")
        self.StartBtn_24 = QtWidgets.QPushButton(self.frame_2)
        self.StartBtn_24.setGeometry(QtCore.QRect(440, 160, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StartBtn_24.setFont(font)
        self.StartBtn_24.setMouseTracking(False)
        self.StartBtn_24.setStyleSheet("border: none;\n"
"color: green;\n"
"\n"
"QPushButton::pressed \n"
"{ \n"
"    color: white;\n"
" }\n"
"\n"
"QPushButton::hover\n"
"{\n"
"     text-decoration: underline; \n"
"    text-decoration-color: green;    \n"
"}")
        self.StartBtn_24.setCheckable(False)
        self.StartBtn_24.setObjectName("StartBtn_24")
        self.StartBtn_25 = QtWidgets.QPushButton(self.frame_2)
        self.StartBtn_25.setGeometry(QtCore.QRect(380, 200, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StartBtn_25.setFont(font)
        self.StartBtn_25.setMouseTracking(False)
        self.StartBtn_25.setStyleSheet("border: none;\n"
"color: green;\n"
"\n"
"QPushButton::pressed \n"
"{ \n"
"    color: white;\n"
" }\n"
"\n"
"QPushButton::hover\n"
"{\n"
"     text-decoration: underline; \n"
"    text-decoration-color: green;    \n"
"}")
        self.StartBtn_25.setCheckable(False)
        self.StartBtn_25.setObjectName("StartBtn_25")
        self.StartBtn_26 = QtWidgets.QPushButton(self.frame_2)
        self.StartBtn_26.setGeometry(QtCore.QRect(440, 200, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StartBtn_26.setFont(font)
        self.StartBtn_26.setMouseTracking(False)
        self.StartBtn_26.setStyleSheet("border: none;\n"
"color: green;\n"
"\n"
"QPushButton::pressed \n"
"{ \n"
"    color: white;\n"
" }\n"
"\n"
"QPushButton::hover\n"
"{\n"
"     text-decoration: underline; \n"
"    text-decoration-color: green;    \n"
"}")
        self.StartBtn_26.setCheckable(False)
        self.StartBtn_26.setObjectName("StartBtn_26")
        self.StartBtn_27 = QtWidgets.QPushButton(self.frame_2)
        self.StartBtn_27.setGeometry(QtCore.QRect(380, 240, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StartBtn_27.setFont(font)
        self.StartBtn_27.setMouseTracking(False)
        self.StartBtn_27.setStyleSheet("border: none;\n"
"color: green;\n"
"\n"
"QPushButton::pressed \n"
"{ \n"
"    color: white;\n"
" }\n"
"\n"
"QPushButton::hover\n"
"{\n"
"     text-decoration: underline; \n"
"    text-decoration-color: green;    \n"
"}")
        self.StartBtn_27.setCheckable(False)
        self.StartBtn_27.setObjectName("StartBtn_27")
        self.StartBtn_28 = QtWidgets.QPushButton(self.frame_2)
        self.StartBtn_28.setGeometry(QtCore.QRect(440, 240, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StartBtn_28.setFont(font)
        self.StartBtn_28.setMouseTracking(False)
        self.StartBtn_28.setStyleSheet("border: none;\n"
"color: green;\n"
"\n"
"QPushButton::pressed \n"
"{ \n"
"    color: white;\n"
" }\n"
"\n"
"QPushButton::hover\n"
"{\n"
"     text-decoration: underline; \n"
"    text-decoration-color: green;    \n"
"}")
        self.StartBtn_28.setCheckable(False)
        self.StartBtn_28.setObjectName("StartBtn_28")
        self.StartBtn_29 = QtWidgets.QPushButton(self.frame_2)
        self.StartBtn_29.setGeometry(QtCore.QRect(380, 280, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StartBtn_29.setFont(font)
        self.StartBtn_29.setMouseTracking(False)
        self.StartBtn_29.setStyleSheet("border: none;\n"
"color: green;\n"
"\n"
"QPushButton::pressed \n"
"{ \n"
"    color: white;\n"
" }\n"
"\n"
"QPushButton::hover\n"
"{\n"
"     text-decoration: underline; \n"
"    text-decoration-color: green;    \n"
"}")
        self.StartBtn_29.setCheckable(False)
        self.StartBtn_29.setObjectName("StartBtn_29")
        self.StartBtn_30 = QtWidgets.QPushButton(self.frame_2)
        self.StartBtn_30.setGeometry(QtCore.QRect(440, 280, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.StartBtn_30.setFont(font)
        self.StartBtn_30.setMouseTracking(False)
        self.StartBtn_30.setStyleSheet("border: none;\n"
"color: green;\n"
"\n"
"QPushButton::pressed \n"
"{ \n"
"    color: white;\n"
" }\n"
"\n"
"QPushButton::hover\n"
"{\n"
"     text-decoration: underline; \n"
"    text-decoration-color: green;    \n"
"}")
        self.StartBtn_30.setCheckable(False)
        self.StartBtn_30.setObjectName("StartBtn_30")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(30, 10, 12, 22))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: orange;\n"
"")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 14, 22))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: red;\n"
"")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(40, 10, 13, 22))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: Yellow;\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(60, 10, 9, 22))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: blue;\n"
"")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(50, 10, 12, 22))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: green;\n"
"")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(70, 10, 12, 22))
        font = QtGui.QFont()
        font.setFamily("Ravie")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: purple;\n"
"")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ExitBtn_3.setText(_translate("MainWindow", "Return"))
        self.label_10.setText(_translate("MainWindow", "Score"))
        self.StartBtn.setText(_translate("MainWindow", "1"))
        self.StartBtn_2.setText(_translate("MainWindow", "2"))
        self.StartBtn_3.setText(_translate("MainWindow", "3"))
        self.StartBtn_4.setText(_translate("MainWindow", "6"))
        self.StartBtn_5.setText(_translate("MainWindow", "7"))
        self.StartBtn_6.setText(_translate("MainWindow", "9"))
        self.StartBtn_7.setText(_translate("MainWindow", "8"))
        self.StartBtn_8.setText(_translate("MainWindow", "4"))
        self.StartBtn_9.setText(_translate("MainWindow", "5"))
        self.StartBtn_10.setText(_translate("MainWindow", "10"))
        self.StartBtn_11.setText(_translate("MainWindow", "Greg"))
        self.StartBtn_12.setText(_translate("MainWindow", "600"))
        self.StartBtn_13.setText(_translate("MainWindow", "500"))
        self.StartBtn_14.setText(_translate("MainWindow", "AI"))
        self.StartBtn_15.setText(_translate("MainWindow", "500"))
        self.StartBtn_16.setText(_translate("MainWindow", "Noob"))
        self.StartBtn_17.setText(_translate("MainWindow", "400"))
        self.StartBtn_18.setText(_translate("MainWindow", "Alice"))
        self.StartBtn_19.setText(_translate("MainWindow", "AI"))
        self.StartBtn_20.setText(_translate("MainWindow", "300"))
        self.StartBtn_21.setText(_translate("MainWindow", "Fred"))
        self.StartBtn_22.setText(_translate("MainWindow", "200"))
        self.StartBtn_23.setText(_translate("MainWindow", "AI"))
        self.StartBtn_24.setText(_translate("MainWindow", "200"))
        self.StartBtn_25.setText(_translate("MainWindow", "Rose"))
        self.StartBtn_26.setText(_translate("MainWindow", "200"))
        self.StartBtn_27.setText(_translate("MainWindow", "Caitlyn:"))
        self.StartBtn_28.setText(_translate("MainWindow", "100"))
        self.StartBtn_29.setText(_translate("MainWindow", "Ted"))
        self.StartBtn_30.setText(_translate("MainWindow", "0"))
        self.label_8.setText(_translate("MainWindow", "e"))
        self.label_3.setText(_translate("MainWindow", "T"))
        self.label_4.setText(_translate("MainWindow", "t"))
        self.label_7.setText(_translate("MainWindow", "i"))
        self.label_5.setText(_translate("MainWindow", "r"))
        self.label_6.setText(_translate("MainWindow", "s"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
